server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: jdbc:h2:/Users/428145/Documents/DEVELOPMENT/BarbourBpmDemo/db/barbour
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true